- hosts: all
  tasks:
    - debug:
        msg: Hello world!
#    - name: install black pip package 
#      pip:
#        name: black==23.7.0
#    - name: Run black
#      command: python3 -m black . --check
