- hosts: all
  tasks:
    - debug:
        msg: Hello world!
    - shell: ls -l src/gerrit/chess_simulator/ci
    - shell: src/gerrit/chess_simulator/ci/check.sh

#    - name: install black pip package
#      pip:
#        name: black==23.7.0
#    - name: Run black
#      command: python3 -m black . --check
